name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  
  workflow_dispatch:
jobs:

  test-security-build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
     
      run: |
        pip install --upgrade pip==26.1.2
        pip install --upgrade setuptools
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest

    - name: Run Bandit
      run: |
        bandit -r . --exclude ./tests
        
    - name: Run pip-audit
      continue-on-error: true
      run: |
        pip-audit

    - name: Build Docker Image
      run: |
        docker build -t engine-monitor .
